///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesFruitsIcon = 'assets/images/fruits_icon.png';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesIconCheck = 'assets/images/icon_check.png';
  static const String imagesPageViewItem1BackgroundImage =
      'assets/images/page_view_item1_background_image.png';
  static const String imagesPageViewItem1Image =
      'assets/images/page_view_item1_image.png';
  static const String imagesPageViewItem2BackgroundImage =
      'assets/images/page_view_item2_background_image.png';
  static const String imagesPageViewItem2Image =
      'assets/images/page_view_item2_image.png';
  static const String imagesPlant = 'assets/images/plant.png';
  static const String imagesIconNotification =
      'assets/images/icon_notification.png';
  static const String imagesSplashCircle = 'assets/images/splash_circle.png';
  static const String imagesImageProfile = 'assets/images/image_profile.png';
  static const String imagesAppleIcon = 'assets/images/apple_icon.png';
  static const String imagesFacebookIcon = 'assets/images/facebook_icon.png';
  static const String imagesGoogleIcon = 'assets/images/google_icon.png';

  static const String imagesFilterIcon = 'assets/images/fliter_icon.png';
  static const String imagesIconSearch = 'assets/images/icon_search.png';
  static const String imagesTestImag = 'assets/images/test_imag.png';
  static const String imagesFeaturedItemBackground =
      'assets/images/featured_item_background.png';
  static const String boldProducts = 'assets/images/bold/element-3.png';
  static const String boldHome = 'assets/images/bold/home.png';
  static const String boldShoppingCart = 'assets/images/bold/shopping-cart.png';
  static const String boldUser = 'assets/images/bold/user.png';
  static const String outlineProducts = 'assets/images/outline/element-3.png';
  static const String outlineHome = 'assets/images/outline/home.png';
  static const String outlineShoppingCart =
      'assets/images/outline/shopping-cart.png';
  static const String outlineUser = 'assets/images/outline/user.png';
  static const String imagesFliter2 = 'assets/images/fliter2.png';
  static const String imagesTrash = 'assets/images/trash.png';
}
