// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoD7ujOpBe_u6nJb9nHxcwEZvhCbEuV9Q',
    appId: '1:960581839353:web:002167172e5040b1c3b528',
    messagingSenderId: '960581839353',
    projectId: 'fruit-hub-aeb44',
    authDomain: 'fruit-hub-aeb44.firebaseapp.com',
    storageBucket: 'fruit-hub-aeb44.firebasestorage.app',
    measurementId: 'G-W60M4L8G0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGmCDHPACm-D4tykGFsJ1jUTqrVnv3bA8',
    appId: '1:960581839353:android:cf2faedfcb6eb80bc3b528',
    messagingSenderId: '960581839353',
    projectId: 'fruit-hub-aeb44',
    storageBucket: 'fruit-hub-aeb44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlyPLd0oQkdJXJZkuwIuJvW593XxBsXjc',
    appId: '1:960581839353:ios:003a58cd0e72bebbc3b528',
    messagingSenderId: '960581839353',
    projectId: 'fruit-hub-aeb44',
    storageBucket: 'fruit-hub-aeb44.firebasestorage.app',
    iosBundleId: 'com.example.fruitsEcommerec',
  );
}
